# Generated by Django 5.2.5 on 2025-08-18 15:02

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否發布')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否為精選')),
                ('order', models.PositiveIntegerField(default=0, help_text='數字越小排序越前', verbose_name='排序')),
                ('main_image', models.ImageField(help_text='建議尺寸：800x600px', upload_to='artworks/', verbose_name='主要圖片')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='artworks/thumbnails/', verbose_name='縮圖')),
                ('medium', models.CharField(blank=True, help_text='例如：絲綢、棉布、金線等', max_length=100, verbose_name='媒材')),
                ('dimensions', models.CharField(blank=True, help_text='例如：30cm x 40cm', max_length=100, verbose_name='尺寸')),
                ('year_created', models.PositiveIntegerField(blank=True, null=True, verbose_name='創作年份')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArtworkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_categories', to='artworks.artwork')),
                ('category', models.ForeignKey(limit_choices_to={'category_type': 'artwork'}, on_delete=django.db.models.deletion.CASCADE, related_name='category_artworks', to='common.category')),
            ],
            options={
                'verbose_name': '作品分類關聯',
                'verbose_name_plural': '作品分類關聯',
                'unique_together': {('artwork', 'category')},
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='categories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category_type': 'artwork', 'is_active': True}, related_name='artworks', through='artworks.ArtworkCategory', to='common.category'),
        ),
        migrations.CreateModel(
            name='ArtworkTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('technique', models.CharField(blank=True, help_text='例如：蘇繡、湘繡、粵繡等', max_length=200, verbose_name='技法')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.artwork')),
            ],
            options={
                'verbose_name': '作品 Translation',
                'db_table': 'artworks_artwork_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
