# Generated by Django 5.2.5 on 2025-08-18 15:02

import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='電子郵件')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話號碼')),
                ('subject', models.CharField(max_length=200, verbose_name='主旨')),
                ('message', models.TextField(verbose_name='訊息內容')),
                ('status', models.CharField(choices=[('new', '新訊息'), ('read', '已讀'), ('replied', '已回覆'), ('closed', '已關閉')], default='new', max_length=10, verbose_name='狀態')),
                ('admin_notes', models.TextField(blank=True, verbose_name='管理員備註')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 位址')),
                ('user_agent', models.TextField(blank=True, verbose_name='瀏覽器資訊')),
            ],
            options={
                'verbose_name': '聯絡表單',
                'verbose_name_plural': '聯絡表單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話號碼')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('business_hours', models.TextField(blank=True, verbose_name='營業時間')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='經度')),
            ],
            options={
                'verbose_name': '聯絡資訊',
                'verbose_name_plural': '聯絡資訊',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否顯示')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '常見問題',
                'verbose_name_plural': '常見問題',
                'ordering': ['order', 'created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('wechat', '微信'), ('line', 'LINE'), ('other', '其他')], max_length=20, verbose_name='平台')),
                ('url', models.URLField(verbose_name='連結網址')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='用戶名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否顯示')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '社群媒體',
                'verbose_name_plural': '社群媒體',
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('company_name', models.CharField(default='慧繡雅集', max_length=100, verbose_name='公司名稱')),
                ('description', models.TextField(blank=True, verbose_name='簡介')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='contact.contactinfo')),
            ],
            options={
                'verbose_name': '聯絡資訊 Translation',
                'db_table': 'contact_contactinfo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FAQTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question', models.CharField(max_length=300, verbose_name='問題')),
                ('answer', models.TextField(verbose_name='答案')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='contact.faq')),
            ],
            options={
                'verbose_name': '常見問題 Translation',
                'db_table': 'contact_faq_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
