# Generated by Django 5.2.5 on 2025-08-18 15:02

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='慧繡雅集', max_length=100, verbose_name='網站名稱')),
                ('posts_per_page', models.PositiveIntegerField(default=10, verbose_name='每頁文章數')),
                ('allow_comments', models.BooleanField(default=False, verbose_name='允許留言')),
            ],
            options={
                'verbose_name': '部落格設定',
                'verbose_name_plural': '部落格設定',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否發布')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否為精選')),
                ('order', models.PositiveIntegerField(default=0, help_text='數字越小排序越前', verbose_name='排序')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='網址別名')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='發布時間')),
                ('featured_image', models.ImageField(blank=True, help_text='建議尺寸：1200x630px', null=True, upload_to='blog/posts/', verbose_name='特色圖片')),
                ('author_name', models.CharField(default='慧繡雅集', max_length=100, verbose_name='作者名稱')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='瀏覽次數')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(limit_choices_to={'category_type': 'blog'}, on_delete=django.db.models.deletion.CASCADE, related_name='category_posts', to='common.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='blog.post')),
            ],
            options={
                'verbose_name': '文章分類關聯',
                'verbose_name_plural': '文章分類關聯',
                'unique_together': {('post', 'category')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category_type': 'blog', 'is_active': True}, related_name='posts', through='blog.PostCategory', to='common.category'),
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('excerpt', models.TextField(blank=True, help_text='用於文章列表顯示，留空會自動從內容擷取', verbose_name='摘要')),
                ('meta_description', models.CharField(blank=True, help_text='搜索引擎顯示的描述', max_length=160, verbose_name='SEO 描述')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.post')),
            ],
            options={
                'verbose_name': '文章 Translation',
                'db_table': 'blog_post_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
