# Generated by Django 5.2.5 on 2025-08-23 14:22

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='年份')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否顯示')),
            ],
            options={
                'verbose_name': '成就獎項',
                'verbose_name_plural': '成就獎項',
                'ordering': ['year', 'order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('section', models.CharField(choices=[('hero', '首頁主視覺'), ('master', '大師介紹'), ('footer', '頁尾資訊')], max_length=20, unique=True, verbose_name='區塊類型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site_content/hero/', verbose_name='主視覺圖片')),
                ('master_image', models.ImageField(blank=True, null=True, upload_to='site_content/master/', verbose_name='大師照片')),
            ],
            options={
                'verbose_name': '網站內容',
                'verbose_name_plural': '網站內容',
                'ordering': ['section'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AchievementTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='獎項名稱')),
                ('description', models.TextField(blank=True, verbose_name='獎項描述')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='common.achievement')),
            ],
            options={
                'verbose_name': '成就獎項 Translation',
                'db_table': 'common_achievement_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteContentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('hero_title', models.CharField(blank=True, max_length=100, verbose_name='主標題')),
                ('hero_subtitle', models.CharField(blank=True, max_length=100, verbose_name='副標題')),
                ('hero_description', models.TextField(blank=True, verbose_name='描述')),
                ('hero_cta_text', models.CharField(blank=True, max_length=50, verbose_name='行動按鈕文字')),
                ('master_title', models.CharField(blank=True, max_length=100, verbose_name='大師區塊標題')),
                ('master_subtitle', models.CharField(blank=True, max_length=200, verbose_name='大師區塊副標題')),
                ('master_description', models.TextField(blank=True, verbose_name='大師介紹')),
                ('master_description2', models.TextField(blank=True, verbose_name='大師介紹2')),
                ('master_achievements_title', models.CharField(blank=True, max_length=100, verbose_name='成就標題')),
                ('master_technique_title', models.CharField(blank=True, max_length=100, verbose_name='技法標題')),
                ('master_technique_desc', models.TextField(blank=True, verbose_name='技法描述')),
                ('footer_description', models.TextField(blank=True, verbose_name='頁尾描述')),
                ('copyright_text', models.CharField(blank=True, max_length=200, verbose_name='版權聲明')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='common.sitecontent')),
            ],
            options={
                'verbose_name': '網站內容 Translation',
                'db_table': 'common_sitecontent_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
